/**
 * @file DiagnosticI18n.h
 * @brief Internationalization translator for AngelScript diagnostic error messages.
 * @ingroup i18n
 */

#pragma once

#include <string>
#include "i18n/LspStrings.h"

namespace angel_lsp::i18n
{
    /**
     * @brief Translates AngelScript diagnostic compiler messages based on locale.
     * @note Thread-safe stateless translation class.
     */
    class DiagnosticI18n
    {
    public:
        /**
         * @brief Translates an AngelScript diagnostic message into the target locale.
         *
         * @param[in] originalMsg The original message generated by AngelScript compiler.
         * @param[in] locale The target locale for translation (e.g. Locale::EN_US or Locale::ES_ES).
         * @return std::string The translated diagnostic string.
         * @note Thread-safe stateless translation method.
         */
        static std::string Translate(const std::string &originalMsg, Locale locale);
    };
}
