# CopyPdbIfExists.cmake
# Copies the target PDB file to destination directory if it exists.
# In Release or MinSizeRel builds on MSVC, PDB files are not generated by default,
# so the copy step must safely succeed when the file is absent.

if(PDB_FILE AND EXISTS "${PDB_FILE}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${PDB_FILE}" "${DEST_DIR}/"
        RESULT_VARIABLE COPY_RES
    )
    if(NOT COPY_RES EQUAL 0)
        message(WARNING "Failed to copy test PDB from '${PDB_FILE}' to '${DEST_DIR}'")
    endif()
endif()
