#pragma once
#include <string>
#include "i18n/LspStrings.h"

namespace i18n
{
    /**
     * @brief Translates an AngelScript diagnostic message based on the given locale.
     *
     * @param originalMsg The original message generated by AngelScript.
     * @param locale The target locale for translation.
     * @return std::string The translated string.
     */
    class DiagnosticI18n
    {
    public:
        /**
         * @brief Translates an AngelScript diagnostic message based on the given locale.
         *
         * @param originalMsg The original message generated by AngelScript.
         * @param locale The target locale for translation.
         * @return std::string The translated string.
         */
        static std::string Translate(const std::string &originalMsg, Locale locale);
    };
}
