import os

lines = []
lines.append("// Large AngelScript Benchmark Script (3000 lines)")
lines.append("// Generated for performance and stress testing")
lines.append("")
lines.append("namespace GameMath")
lines.append("{")
lines.append("    class Vector3")
lines.append("    {")
lines.append("        float x, y, z;")
lines.append("        Vector3() { x = 0.0f; y = 0.0f; z = 0.0f; }")
lines.append("        Vector3(float _x, float _y, float _z) { x = _x; y = _y; z = _z; }")
lines.append("        float LengthSq() const { return x * x + y * y + z * z; }")
lines.append("        void Add(const Vector3 &in other) { x += other.x; y += other.y; z += other.z; }")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("interface IEntity")
lines.append("{")
lines.append("    void OnInit();")
lines.append("    void OnUpdate(float dt);")
lines.append("    int GetId() const;")
lines.append("}")
lines.append("")

# Generate 50 classes with methods, loops, calls, and array template usage
class_count = 50
for i in range(class_count):
    lines.append(f"class EntityBase_{i} : IEntity")
    lines.append("    {")
    lines.append(f"        private int m_id_{i};")
    lines.append(f"        private float m_health_{i};")
    lines.append(f"        private string m_name_{i};")
    lines.append(f"        private array<int> m_items_{i};")
    lines.append(f"        private GameMath::Vector3 m_pos_{i};")
    lines.append("")
    lines.append(f"        EntityBase_{i}()")
    lines.append("        {")
    lines.append(f"            m_id_{i} = {i};")
    lines.append(f"            m_health_{i} = 100.0f;")
    lines.append(f'            m_name_{i} = "Entity_{i}";')
    lines.append("        }")
    lines.append("")
    lines.append("        void OnInit() override")
    lines.append("        {")
    lines.append(f"            m_items_{i}.resize(10);")
    lines.append("            for (uint j = 0; j < 10; ++j)")
    lines.append("            {")
    lines.append(f"                m_items_{i}[j] = int(j * {i + 1});")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        void OnUpdate(float dt) override")
    lines.append("        {")
    lines.append(f"            m_pos_{i}.x += dt * 2.0f;")
    lines.append(f"            m_pos_{i}.y += dt * 3.0f;")
    lines.append(f"            if (m_health_{i} > 0.0f)")
    lines.append("            {")
    lines.append(f"                m_health_{i} -= dt * 0.1f;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        int GetId() const override")
    lines.append("        {")
    lines.append(f"            return m_id_{i};")
    lines.append("        }")
    lines.append("")
    lines.append(f"        float ComputeScore(int multiplier) const")
    lines.append("        {")
    lines.append(f"            float score = m_health_{i} * float(multiplier);")
    lines.append(f"            score += m_pos_{i}.LengthSq();")
    lines.append("            return score;")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

# Manager class with calls
lines.append("class SimulationManager")
lines.append("{")
lines.append("    private array<IEntity@> m_entities;")
lines.append("")
lines.append("    void Setup()")
lines.append("    {")
for i in range(class_count):
    lines.append(f"        m_entities.insertLast(EntityBase_{i}());")
lines.append("    }")
lines.append("")
lines.append("    void UpdateAll(float dt)")
lines.append("    {")
lines.append("        for (uint i = 0; i < m_entities.length(); ++i)")
lines.append("        {")
lines.append("            if (m_entities[i] !is null)")
lines.append("            {")
lines.append("                m_entities[i].OnUpdate(dt);")
lines.append("            }")
lines.append("        }")
lines.append("    }")
lines.append("}")
lines.append("")

target_lines = 3000
fn_idx = 0
while len(lines) < target_lines - 15:
    lines.append(f"int HelperFunction_{fn_idx}(int a, int b)")
    lines.append("{")
    lines.append("    int c = a + b;")
    lines.append("    int d = c * 2;")
    lines.append("    if (d > 100)")
    lines.append("    {")
    lines.append("        return d - 100;")
    lines.append("    }")
    lines.append("    return d;")
    lines.append("}")
    lines.append("")
    fn_idx += 1

lines.append("void MainEntry()")
lines.append("{")
lines.append("    SimulationManager sim;")
lines.append("    sim.Setup();")
lines.append("    sim.UpdateAll(0.016f);")
lines.append("}")

while len(lines) < target_lines:
    lines.append(f"// End of benchmark script padding line {len(lines) + 1}")

out_path = os.path.join(os.path.dirname(__file__), "large_script_3000.as")
with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"Successfully generated {out_path} with {len(lines)} lines.")
